urls = (
    '/', 'application.controllers.main.index.Index',
    '/404', 'application.controllers.main.notfound.NotFound',
    '/500', 'application.controllers.main.internalerror.InternalError',
    "/login", "application.controllers.main.login.Login",
    "/loginselection", "application.controllers.main.loginselection.LoginSelection",
    "/logout", "application.controllers.main.logout.Logout",
    "/auth/(google)", "application.controllers.main.login.AuthPage",
    "/auth/(google)/callback", "application.controllers.main.login.AuthCallbackPage",
    '/registro', 'application.controllers.main.registro.Insert',
    '/index_asesor','application.controllers.asesor.index.Index',
    '/index_asesoria','application.controllers.asesoria.index.Index',
    '/insert_asesoria','application.controllers.asesoria.insert.Insert',
    '/perfil_asesor/(.*)','application.controllers.asesor.perfil.Perfil',
    '/editar_asesor/(.*)','application.controllers.asesor.editar.Editar',
    '/perfil/(.*)','application.controllers.asesor.perfil_e.Perfil',
    '/editar_asesoria/(.*)', 'application.controllers.asesoria.edit.Editar',
    '/api_asesor/?', 'application.api.asesor.api_asesor.Api_asesor',
    '/api_asesorias/?', 'application.api.asesorias.api_asesorias.Api_asesorias',
    '/api_valoracion/?', 'application.api.valoracion.api_valoracion.Api_valoracion',
    '/api_users/?', 'application.api.users.api_users.Api_users',
    '/valorar/(.*)', 'application.controllers.asesoria.valoracion.Valorar',
    '/reporte_asesor/(.*)', 'application.controllers.asesoria.reporte_asesor.Reporte',
    '/reporte_alumno/(.*)', 'application.controllers.asesoria.reporte_alumno.Reporte',
    '/evaluacion_asesor/(.*)', 'application.controllers.asesoria.evaluacion_asesor.Evaluar',
    '/evaluacion_alumno/(.*)', 'application.controllers.asesoria.evaluacion_alumno.Evaluar',
    '/api_evaluacion_asesor/?', 'application.api.evaluacion_asesor.api_evaluacion_asesor.Api_evaluacion_asesor',
   )